############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1



[[main]]
name = "Topics"
url = "categories/"
weight = 2


[[main]]
name = "About"
url = "about/"
weight = 3



#[[main]]
#name = "Contact"
#url = "contact/"
#weight = 3

#[[main]]
#name = "Tags"
#url = "tags/"
#weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2


#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 4
