about_widget_content = "Here you will find content related to Machine Learning and Deep Learning topics"
address = "Bangalore"
author = "Sreejith"
contact_form_action = "#"
copyright = ""
custom_script = ""
description = "This is meta description"
email = "sreejith1312@gmail.com"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = ""
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = ""
link = ""
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Here you will find content related to Machine Learning and Deep Learning topics"
enable = true
image = "images/banner.png"
title_large = "Machine Learning Blog **!**"
title_small = ""
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
